platform :ios, '14.1'
use_frameworks!
inhibit_all_warnings!

target 'Restaurants' do
  pod 'BottomPopup', '~> 0.6'
  pod 'Argo', '~> 5.0'
  pod 'Curry', '~> 5.0'
  pod 'FoursquareAPIClient', '~> 5.0'
  pod 'SwiftLocation', '~> 5.0'
  pod 'CombineCocoa', '~> 0.2'
  pod 'GSMessages', '~> 1.7'
  pod 'LocationProvider', :git => 'https://github.com/skyylex/LocationProvider.git', :commit => '5f9ba301b2f77c2cf5a0ed2b1ff1ea6e2912c6e3'
end

target 'RestaurantsTests' do
  pod 'FoursquareAPIClient', '~> 5.0'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.1'
      end
    end
end
